USE ROLE ACCOUNTADMIN;

-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE NBA_ROLE;
GRANT ROLE NBA_ROLE TO ROLE SYSADMIN;
GRANT ROLE NBA_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE NBA_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE NBA_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE NBA_ROLE;

-- Databases
CREATE OR REPLACE DATABASE NBA_DB;
GRANT OWNERSHIP ON DATABASE NBA_DB TO ROLE NBA_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE NBA_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE NBA_WH TO ROLE NBA_ROLE;


-- ----------------------------------------------------------------------------
-- Step #3: Create the database level objects
-- ----------------------------------------------------------------------------
USE ROLE NBA_ROLE;
USE WAREHOUSE NBA_WH;
USE DATABASE NBA_DB;

-- Schemas
CREATE OR REPLACE SCHEMA EXTERNAL;
CREATE OR REPLACE SCHEMA RAW_NBA;
CREATE OR REPLACE SCHEMA HARMONIZED;
CREATE OR REPLACE SCHEMA ANALYTICS;
